name: website
run-name: ${{ github.actor }} has added GitHub Actions
on:
    push:
      branches:
        - main
        - dev
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: echo "This is running"